spring.application.name=school_test
pring.datasource.url=jdbc:postgresql://localhost:5432/hogwarts
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto = update
spring.datasource.driver-class-name=org.postgresql.Driver